"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 
1 and 2 , the first 10 terms will be: 

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

class euler_problem_2:

    def __init__(self):
        pass

    def fibonacci_even_sum(self, limit: int):
        
        term_1 = 1
        term_2 = 2

        sum_even_values = 2 #init on 2 becuase i have the value

        while True:

            new_fibo = term_1 + term_2 
            if new_fibo > limit:
                break   
            
            if new_fibo % 2 == 0:
                sum_even_values += new_fibo #getting the solution
            
            term_1 = term_2
            term_2 = new_fibo   #updating values
        
        return sum_even_values


    #chat gpt solution
    def fibonacci_even_sum_ChatGPT(self, limit: int):
        a, b = 1, 2
        total = 0
        while a <= limit:
            if a % 2 == 0:
                total += a
            a, b = b, a + b
        return total



